only_rules:
  - empty_count
  - trailing_whitespace
  - force_cast
  - force_try
  - redundant_void_return
  - unneeded_break_in_switch
  - unused_closure_parameter
  - void_return

excluded:
  - .build
  - Tests

reporter: github-actions-logging
